spring:
  application:
    name: bankcards-api
  
  datasource:
    url: jdbc:postgresql://localhost:5432/bankcards
    username: bankuser
    password: bankpass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  liquibase:
    change-log: classpath:db/migration/changelog-master.xml
    enabled: true
  
  security:
    jwt:
      secret: your-secret-key-here-make-it-very-long-and-secure-in-production
      expiration: 86400000 # 24 часа

server:
  port: 8080

logging:
  level:
    com.example.bankcards: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
